<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="footer-container">
 <div class="box-footer">
     <h3 class="heading">Fashion Mart</h3>
 <img src="{{media url='web/images/coffeelogo.jpg'}}" alt="image not found" />
 </div>

 <div class="box-footer">
     <h3 class="heading">Links</h3>
     <ul>
     <li><a href="http://127.0.0.1/magento/megento3/">Home</a></li>
         <li><a href="http://127.0.0.1/magento/megento3/cloths.html">Clothes</a></li>
         <li><a href="http://127.0.0.1/magento/megento3/product-test.html">Product/Test</a></li>
         <li><a href="http://127.0.0.1/magento/megento3/health-packages.html">Health Packages</a></li>
         <li><a href="http://127.0.0.1/magento/megento3/contact.html">contact Us</a></li>
     </ul>
 </div>
 <div class="box-footer">
     <h3 class="heading">Links For Costumer's</h3>

     <ul>
     <li><a href="http://127.0.0.1/magento/megento3/coustomer/account">My Accounts</a></li>
         <li><a href="">Sign In</a></li>
         <li><a href="">Create Account</a></li>
         <li><a href="http://127.0.0.1/magento/megento3/cloths.html">Purchage</a></li>
         <li><a href="">My Orders</a></li>
     </ul>

 </div>
 <div class="box-footer">
     <h3 class="heading">Subscribe to our Newsletter</h3>

     <form action="/action_page.php">
  <div class="container" style="background-color:white">
    <input type="text" placeholder="Name" name="name" required><br/>
    <input type="text" placeholder="Email address" name="mail" required><br/>
    <label>
      <input type="checkbox" checked="checked" name="subscribe"> Daily Newsletter
    </label>
  </div><br/>

  <div class="container">
    <input type="submit" style="background:blue;" value="Subscribe">
  </div>
</form>
 </div>

</div>


